zh:
  contentDir: "content/zh/"
  languageName: "简体中文"
  title: "RadonDB 开源社区"
  weight: 10
  params:
    description: "一个面向云原生、容器化的数据库开源社区"
    kubesphereVideoPoster: "/images/RadonDB.png"
    kubesphereVideo: "https://dbg-files.pek3b.qingstor.com/radondb_website/video/%E5%A6%82%E4%BD%95%E5%9C%A8%20Kubernetes%20%E4%B8%8A%E9%83%A8%E7%BD%B2%20RadonDB%20MySQL/%E5%B8%A6BGM/%E9%83%A8%E7%BD%B2%20RadonDB%20MySQL%20%E9%9B%86%E7%BE%A4.mp4"
    # 关于我们页面中video的封面
    aboutVideoPoster: "/images/video.png"
    aboutVideo: "https://dbg-files.pek3b.qingstor.com/radondb_website/video/RadonDB%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D.mp4"

en:
  contentDir: "content/en/"
  languageName: "EN"
  title: "RadonDB OpenSource"
  weight: 20
  params:
    description: "home descriptions"
    kubesphereVideoPoster: "/images/RadonDB.png"
    kubesphereVideo: "https://dbg-files.pek3b.qingstor.com/radondb_website/video/%E5%A6%82%E4%BD%95%E5%9C%A8%20Kubernetes%20%E4%B8%8A%E9%83%A8%E7%BD%B2%20RadonDB%20MySQL/%E5%B8%A6BGM/%E9%83%A8%E7%BD%B2%20RadonDB%20MySQL%20%E9%9B%86%E7%BE%A4.mp4"
    aboutVideoPoster: "/images/intro-poster.png"
    aboutVideo: "https://dbg-files.pek3b.qingstor.com/radondb_website/video/RadonDB%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D.mp4"
